
language: objective-c

before_install:
- gem install cocoapods

script:
- cd Demo
- pod repo update --silent
- pod update
- xctool -workspace NBUKitDemo.xcworkspace -scheme 'NBUKitDemo' -configuration Release -sdk iphonesimulator -arch i386 build
